import type { Lead, LeadActivity, LeadNote } from './types';

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-01', organization_id: 'mock-org-1', phone: '+905321234567', email: 'ahmet.yilmaz@gmail.com',
    external_platform_id: null, first_name: 'Ahmet', last_name: 'Yılmaz', full_name: 'Ahmet Yılmaz',
    company: 'Yılmaz Teknoloji', job_title: 'CEO', city: 'İstanbul', country: 'Türkiye',
    stage_id: 'stage-1', assigned_to: 'mock-user-1', score: 85,
    source_platform: 'meta_lead_form', campaign_name: 'Instagram Kampanya Q1', ad_set_name: 'Lookalike Hedef', ad_name: 'Video Reklam 1',
    form_name: 'İletişim Formu', meta_lead_id: null, meta_page_id: null, utm_source: 'instagram', utm_medium: 'paid', utm_campaign: 'q1_lead_gen', utm_content: null, utm_term: null,
    tags: ['sıcak', 'VIP'], custom_fields: {}, notes_count: 2, activities_count: 5,
    last_activity_at: new Date(Date.now() - 3600000).toISOString(), first_seen_at: '2026-03-15T10:00:00Z',
    created_at: '2026-03-15T10:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-1', organization_id: 'mock-org-1', name: 'Yeni', slug: 'new', color: '#10b981', position: 0, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-02', organization_id: 'mock-org-1', phone: '+905551112233', email: 'elif.kaya@outlook.com',
    external_platform_id: null, first_name: 'Elif', last_name: 'Kaya', full_name: 'Elif Kaya',
    company: 'Kaya Danışmanlık', job_title: 'Pazarlama Müdürü', city: 'Ankara', country: 'Türkiye',
    stage_id: 'stage-2', assigned_to: 'mock-user-1', score: 72,
    source_platform: 'whatsapp', campaign_name: 'WhatsApp Broadcast', ad_set_name: null, ad_name: null,
    form_name: null, meta_lead_id: null, meta_page_id: null, utm_source: 'whatsapp', utm_medium: 'organic', utm_campaign: null, utm_content: null, utm_term: null,
    tags: ['geri-aranacak'], custom_fields: {}, notes_count: 1, activities_count: 3,
    last_activity_at: new Date(Date.now() - 7200000).toISOString(), first_seen_at: '2026-03-18T14:00:00Z',
    created_at: '2026-03-18T14:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-2', organization_id: 'mock-org-1', name: 'İletişime Geçildi', slug: 'contacted', color: '#3b82f6', position: 1, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-03', organization_id: 'mock-org-1', phone: '+905443217890', email: 'mehmet.demir@company.com',
    external_platform_id: null, first_name: 'Mehmet', last_name: 'Demir', full_name: 'Mehmet Demir',
    company: 'Demir İnşaat', job_title: 'Genel Müdür', city: 'İzmir', country: 'Türkiye',
    stage_id: 'stage-3', assigned_to: null, score: 60,
    source_platform: 'instagram_dm', campaign_name: 'Meta Lead Gen Mart', ad_set_name: 'Retargeting', ad_name: 'Carousel Reklam',
    form_name: null, meta_lead_id: null, meta_page_id: null, utm_source: 'instagram', utm_medium: 'paid', utm_campaign: 'mart_retarget', utm_content: null, utm_term: null,
    tags: ['demo-istedi', 'sıcak'], custom_fields: {}, notes_count: 0, activities_count: 4,
    last_activity_at: new Date(Date.now() - 86400000).toISOString(), first_seen_at: '2026-03-10T09:00:00Z',
    created_at: '2026-03-10T09:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-3', organization_id: 'mock-org-1', name: 'Nitelikli', slug: 'qualified', color: '#8b5cf6', position: 2, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-04', organization_id: 'mock-org-1', phone: '+905367891234', email: 'zeynep.arslan@firma.com',
    external_platform_id: null, first_name: 'Zeynep', last_name: 'Arslan', full_name: 'Zeynep Arslan',
    company: 'Arslan Medya', job_title: 'CMO', city: 'İstanbul', country: 'Türkiye',
    stage_id: 'stage-4', assigned_to: 'mock-user-1', score: 90,
    source_platform: 'meta_lead_form', campaign_name: 'Instagram Kampanya Q1', ad_set_name: 'Broad Hedef', ad_name: 'Story Reklam',
    form_name: 'Demo Talep Formu', meta_lead_id: null, meta_page_id: null, utm_source: 'facebook', utm_medium: 'paid', utm_campaign: 'q1_demo', utm_content: null, utm_term: null,
    tags: ['VIP', 'demo-istedi'], custom_fields: {}, notes_count: 3, activities_count: 8,
    last_activity_at: new Date(Date.now() - 1800000).toISOString(), first_seen_at: '2026-03-05T16:00:00Z',
    created_at: '2026-03-05T16:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-4', organization_id: 'mock-org-1', name: 'Toplantı', slug: 'meeting', color: '#f59e0b', position: 3, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-05', organization_id: 'mock-org-1', phone: '+905421239876', email: 'can.ozturk@email.com',
    external_platform_id: null, first_name: 'Can', last_name: 'Öztürk', full_name: 'Can Öztürk',
    company: 'Öztürk Yazılım', job_title: 'CTO', city: 'Bursa', country: 'Türkiye',
    stage_id: 'stage-5', assigned_to: 'mock-user-1', score: 78,
    source_platform: 'messenger', campaign_name: 'Meta Lead Gen Mart', ad_set_name: 'Teknoloji Hedef', ad_name: 'Single Image',
    form_name: null, meta_lead_id: null, meta_page_id: null, utm_source: 'facebook', utm_medium: 'paid', utm_campaign: 'mart_tech', utm_content: null, utm_term: null,
    tags: ['teklif-gonderildi'], custom_fields: {}, notes_count: 1, activities_count: 6,
    last_activity_at: new Date(Date.now() - 43200000).toISOString(), first_seen_at: '2026-03-01T11:00:00Z',
    created_at: '2026-03-01T11:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-5', organization_id: 'mock-org-1', name: 'Teklif', slug: 'offer', color: '#f97316', position: 4, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-06', organization_id: 'mock-org-1', phone: '+905339876543', email: 'ayse.celik@gmail.com',
    external_platform_id: null, first_name: 'Ayşe', last_name: 'Çelik', full_name: 'Ayşe Çelik',
    company: 'Çelik Moda', job_title: 'Kurucu', city: 'Antalya', country: 'Türkiye',
    stage_id: 'stage-6', assigned_to: 'mock-user-1', score: 95,
    source_platform: 'website', campaign_name: null, ad_set_name: null, ad_name: null,
    form_name: 'Website İletişim', meta_lead_id: null, meta_page_id: null, utm_source: 'google', utm_medium: 'organic', utm_campaign: null, utm_content: null, utm_term: null,
    tags: ['VIP', 'kazanıldı'], custom_fields: {}, notes_count: 4, activities_count: 12,
    last_activity_at: new Date(Date.now() - 172800000).toISOString(), first_seen_at: '2026-02-20T08:00:00Z',
    created_at: '2026-02-20T08:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-6', organization_id: 'mock-org-1', name: 'Kazanıldı', slug: 'won', color: '#22c55e', position: 5, is_won: true, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-07', organization_id: 'mock-org-1', phone: '+905551234890', email: 'burak.sahin@test.com',
    external_platform_id: null, first_name: 'Burak', last_name: 'Şahin', full_name: 'Burak Şahin',
    company: 'Şahin Otomotiv', job_title: 'Satış Müdürü', city: 'İstanbul', country: 'Türkiye',
    stage_id: 'stage-7', assigned_to: null, score: 25,
    source_platform: 'meta_lead_form', campaign_name: 'Instagram Kampanya Q1', ad_set_name: 'Cold Hedef', ad_name: 'Video Reklam 2',
    form_name: 'İletişim Formu', meta_lead_id: null, meta_page_id: null, utm_source: 'instagram', utm_medium: 'paid', utm_campaign: 'q1_cold', utm_content: null, utm_term: null,
    tags: ['soğuk'], custom_fields: {}, notes_count: 0, activities_count: 2,
    last_activity_at: new Date(Date.now() - 604800000).toISOString(), first_seen_at: '2026-03-12T13:00:00Z',
    created_at: '2026-03-12T13:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-7', organization_id: 'mock-org-1', name: 'Kaybedildi', slug: 'lost', color: '#ef4444', position: 6, is_won: false, is_lost: true, created_at: '' },
  },
  {
    id: 'lead-08', organization_id: 'mock-org-1', phone: '+905441237654', email: 'selin.yildiz@company.com',
    external_platform_id: null, first_name: 'Selin', last_name: 'Yıldız', full_name: 'Selin Yıldız',
    company: 'Yıldız Eğitim', job_title: 'Direktör', city: 'Ankara', country: 'Türkiye',
    stage_id: 'stage-1', assigned_to: null, score: 45,
    source_platform: 'instagram_dm', campaign_name: 'Meta Lead Gen Mart', ad_set_name: 'Eğitim Hedef', ad_name: 'Reel Reklam',
    form_name: null, meta_lead_id: null, meta_page_id: null, utm_source: 'instagram', utm_medium: 'paid', utm_campaign: 'mart_edu', utm_content: null, utm_term: null,
    tags: ['yeni'], custom_fields: {}, notes_count: 0, activities_count: 1,
    last_activity_at: new Date(Date.now() - 14400000).toISOString(), first_seen_at: '2026-03-28T15:00:00Z',
    created_at: '2026-03-28T15:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-1', organization_id: 'mock-org-1', name: 'Yeni', slug: 'new', color: '#10b981', position: 0, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-09', organization_id: 'mock-org-1', phone: '+905367654321', email: 'emre.koc@firma.com',
    external_platform_id: null, first_name: 'Emre', last_name: 'Koç', full_name: 'Emre Koç',
    company: 'Koç Dijital', job_title: 'Pazarlama Uzmanı', city: 'İzmir', country: 'Türkiye',
    stage_id: 'stage-2', assigned_to: 'mock-user-1', score: 55,
    source_platform: 'whatsapp', campaign_name: 'WhatsApp Broadcast', ad_set_name: null, ad_name: null,
    form_name: null, meta_lead_id: null, meta_page_id: null, utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null, utm_term: null,
    tags: ['geri-aranacak', 'ilgili'], custom_fields: {}, notes_count: 1, activities_count: 3,
    last_activity_at: new Date(Date.now() - 28800000).toISOString(), first_seen_at: '2026-03-22T10:30:00Z',
    created_at: '2026-03-22T10:30:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-2', organization_id: 'mock-org-1', name: 'İletişime Geçildi', slug: 'contacted', color: '#3b82f6', position: 1, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-10', organization_id: 'mock-org-1', phone: '+905529871234', email: 'deniz.aktas@gmail.com',
    external_platform_id: null, first_name: 'Deniz', last_name: 'Aktaş', full_name: 'Deniz Aktaş',
    company: 'Aktaş Holding', job_title: 'Yönetim Kurulu Üyesi', city: 'İstanbul', country: 'Türkiye',
    stage_id: 'stage-3', assigned_to: 'mock-user-1', score: 88,
    source_platform: 'meta_lead_form', campaign_name: 'Instagram Kampanya Q1', ad_set_name: 'Enterprise Hedef', ad_name: 'Video Reklam 3',
    form_name: 'Kurumsal Talep', meta_lead_id: null, meta_page_id: null, utm_source: 'facebook', utm_medium: 'paid', utm_campaign: 'q1_enterprise', utm_content: null, utm_term: null,
    tags: ['VIP', 'sıcak', 'enterprise'], custom_fields: {}, notes_count: 2, activities_count: 7,
    last_activity_at: new Date(Date.now() - 5400000).toISOString(), first_seen_at: '2026-03-08T09:00:00Z',
    created_at: '2026-03-08T09:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-3', organization_id: 'mock-org-1', name: 'Nitelikli', slug: 'qualified', color: '#8b5cf6', position: 2, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-11', organization_id: 'mock-org-1', phone: '+905331119988', email: 'fatma.erdogan@outlook.com',
    external_platform_id: null, first_name: 'Fatma', last_name: 'Erdoğan', full_name: 'Fatma Erdoğan',
    company: 'Erdoğan Tekstil', job_title: 'İhracat Müdürü', city: 'Bursa', country: 'Türkiye',
    stage_id: 'stage-4', assigned_to: null, score: 67,
    source_platform: 'messenger', campaign_name: 'Meta Lead Gen Mart', ad_set_name: 'Tekstil Hedef', ad_name: 'Collection Ad',
    form_name: null, meta_lead_id: null, meta_page_id: null, utm_source: 'facebook', utm_medium: 'paid', utm_campaign: 'mart_tekstil', utm_content: null, utm_term: null,
    tags: ['toplantı-planlandı'], custom_fields: {}, notes_count: 1, activities_count: 5,
    last_activity_at: new Date(Date.now() - 10800000).toISOString(), first_seen_at: '2026-03-14T12:00:00Z',
    created_at: '2026-03-14T12:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-4', organization_id: 'mock-org-1', name: 'Toplantı', slug: 'meeting', color: '#f59e0b', position: 3, is_won: false, is_lost: false, created_at: '' },
  },
  {
    id: 'lead-12', organization_id: 'mock-org-1', phone: '+905447778899', email: 'omer.tas@email.com',
    external_platform_id: null, first_name: 'Ömer', last_name: 'Taş', full_name: 'Ömer Taş',
    company: 'Taş Gayrimenkul', job_title: 'Broker', city: 'Antalya', country: 'Türkiye',
    stage_id: 'stage-1', assigned_to: null, score: 30,
    source_platform: 'website', campaign_name: null, ad_set_name: null, ad_name: null,
    form_name: 'Website İletişim', meta_lead_id: null, meta_page_id: null, utm_source: 'google', utm_medium: 'cpc', utm_campaign: 'search_brand', utm_content: null, utm_term: 'yo dijital',
    tags: ['yeni'], custom_fields: {}, notes_count: 0, activities_count: 1,
    last_activity_at: new Date(Date.now() - 3600000 * 5).toISOString(), first_seen_at: '2026-03-29T17:00:00Z',
    created_at: '2026-03-29T17:00:00Z', updated_at: new Date().toISOString(),
    stage: { id: 'stage-1', organization_id: 'mock-org-1', name: 'Yeni', slug: 'new', color: '#10b981', position: 0, is_won: false, is_lost: false, created_at: '' },
  },
];

export const MOCK_ACTIVITIES: LeadActivity[] = [
  { id: 'act-1', lead_id: 'lead-01', organization_id: 'mock-org-1', user_id: 'mock-user-1', activity_type: 'created', title: 'Lead oluşturuldu', description: 'Meta Lead Form üzerinden geldi', metadata: {}, created_at: '2026-03-15T10:00:00Z' },
  { id: 'act-2', lead_id: 'lead-01', organization_id: 'mock-org-1', user_id: 'mock-user-1', activity_type: 'stage_change', title: 'Aşama değiştirildi', description: 'Yeni → İletişime Geçildi', metadata: {}, created_at: '2026-03-16T11:00:00Z' },
  { id: 'act-3', lead_id: 'lead-01', organization_id: 'mock-org-1', user_id: 'mock-user-1', activity_type: 'note_added', title: 'Not eklendi', description: 'Müşteri toplantı istedi', metadata: {}, created_at: '2026-03-17T14:30:00Z' },
  { id: 'act-4', lead_id: 'lead-01', organization_id: 'mock-org-1', user_id: 'mock-user-1', activity_type: 'email_sent', title: 'E-posta gönderildi', description: 'Teklif e-postası gönderildi', metadata: {}, created_at: '2026-03-18T09:00:00Z' },
  { id: 'act-5', lead_id: 'lead-04', organization_id: 'mock-org-1', user_id: 'mock-user-1', activity_type: 'assigned', title: 'Atandı', description: 'Onur Suay\'a atandı', metadata: {}, created_at: '2026-03-06T10:00:00Z' },
];

export const MOCK_NOTES: LeadNote[] = [
  { id: 'note-1', lead_id: 'lead-01', organization_id: 'mock-org-1', user_id: 'mock-user-1', content: 'Müşteri Q2 başlangıcında toplantı istiyor. Bütçe 50.000 TL civarı.', is_system: false, created_at: '2026-03-17T14:30:00Z', updated_at: '2026-03-17T14:30:00Z', user: { id: 'mock-user-1', email: 'admin@yodijital.com', full_name: 'Onur Suay', avatar_url: null, phone: null, created_at: '', updated_at: '' } },
  { id: 'note-2', lead_id: 'lead-01', organization_id: 'mock-org-1', user_id: 'mock-user-1', content: 'İlk arama yapıldı. Çok ilgili, web sitesi yenileme projesi var.', is_system: false, created_at: '2026-03-16T11:30:00Z', updated_at: '2026-03-16T11:30:00Z', user: { id: 'mock-user-1', email: 'admin@yodijital.com', full_name: 'Onur Suay', avatar_url: null, phone: null, created_at: '', updated_at: '' } },
  { id: 'note-3', lead_id: 'lead-04', organization_id: 'mock-org-1', user_id: 'mock-user-1', content: 'Toplantı 5 Nisan\'da planlandı. Sosyal medya yönetimi + reklam paketi sunulacak.', is_system: false, created_at: '2026-03-20T09:00:00Z', updated_at: '2026-03-20T09:00:00Z', user: { id: 'mock-user-1', email: 'admin@yodijital.com', full_name: 'Onur Suay', avatar_url: null, phone: null, created_at: '', updated_at: '' } },
];
